server:
  port: ${AF_SERVER_PORT:10241}

spring:
  application:
    name: AFile
  profiles:
    active: sqlite
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  boot:
    admin:
      context-path: ${AF_ADMIN_PATH:/spring-boot-admin}
      client:
        url: http://127.0.0.1:${AF_SERVER_PORT:10241}${AF_ADMIN_PATH:/spring-boot-admin}
management:
  endpoints:
    web:
      exposure:
        include: ${AF_MANAGEMENT_ENDPOINTS:health,metrics}

---
spring:
  config:
    activate:
      on-profile: debug

management:
  endpoints:
    web:
      exposure:
        include: ${AF_MANAGEMENT_ENDPOINTS:*}

---
spring:
  config:
    activate:
      on-profile: sqlite

  datasource:
    username: root
    password: root
    url: jdbc:sqlite:${user.home}/.afile/db
    driver-class-name: org.sqlite.JDBC

  flyway:
    enabled: true
    locations: classpath:db/migration/sqlite